name: "Let's SiNAVM!"

on:
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *'

concurrency:
  group: "sinavm-full"
  cancel-in-progress: true

jobs:
  sinavm-full:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Dependencies for HiddifyCli
        run: |
          sudo apt-get update
          sudo apt-get install -y curl tar

      - name: Run Clash API
        run: |
          docker run -d -p 6756:6756 dreamacro/clash --port 6756
          sleep 10 # Wait for Clash to start

      - name: Execute PHP script
        run: |
          set -e
          git pull --rebase
          php -d display_errors get.php
          php -d display_errors config-test.php || true
          php -d display_errors channelsAssets.php
          php -d display_errors duplicate.php
          php -d display_errors sort.php
          php -d display_errors toSingbox.php
          php -d display_errors toClashSurfboard.php
          php -d display_errors hiddifyWarp.php
          
          git config --global user.email "sina2941@gmail.com"
          git config --global user.name "sinabigo"
          git config credential.helper store
          
          git add -A
          git commit -m "🚀 Servers Updated - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          git push

  sinavm-lite:
    runs-on: ubuntu-latest
    needs: sinavm-full 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Dependencies for HiddifyCli
        run: |
          sudo apt-get update
          sudo apt-get install -y curl tar

      - name: Run Clash API
        run: |
          docker run -d -p 6756:6756 dreamacro/clash --port 6756
          sleep 10 # Wait for Clash to start

      - name: Execute PHP script
        run: |
          set -e  
          git pull
          cd lite
          php -d display_errors get.php
          php -d display_errors ../config-test.php || true
          php -d display_errors duplicate.php
          php -d display_errors sort.php
          php -d display_errors toSingbox.php
          php -d display_errors toClashSurfboard.php
          
          git config --global user.email "sina2941@gmail.com"
          git config --global user.name "sinabigo"
          git config credential.helper store
          
          git add -A
          git commit -m "🚀 Servers Updated - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          git push
